# Generated by Django 4.1 on 2024-02-26 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_name', models.CharField(max_length=100)),
                ('crime_start_datetime', models.DateTimeField()),
                ('crime_end_datetime', models.DateTimeField()),
                ('crime_place', models.CharField(max_length=100)),
                ('crim_fact', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VictimModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeapp.crimemodel')),
            ],
        ),
        migrations.CreateModel(
            name='SuspectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('honseki', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('job', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('crime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeapp.crimemodel')),
            ],
        ),
        migrations.AddField(
            model_name='crimemodel',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crimeapp.genremodel'),
        ),
    ]
