# Generated by Django 4.1 on 2024-02-26 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crimeapp', '0002_crimemodel_crime_name_second_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crimemodel',
            old_name='crim_fact',
            new_name='crime_fact',
        ),
    ]
